// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pligrimage.Data;

namespace Pligrimage.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190508083849_forNullData")]
    partial class forNullData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pligrimage.Entities.AlhajjMaster", b =>
                {
                    b.Property<int>("PligrimageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlhajYear");

                    b.Property<string>("BloodGroup");

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<DateTime?>("DateOfEnlistment");

                    b.Property<string>("DoctorNote");

                    b.Property<int>("DocumentId");

                    b.Property<bool>("FitFlag");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<string>("GSM");

                    b.Property<int>("HrmsUnitCode");

                    b.Property<string>("HrmsUnitDesc");

                    b.Property<int>("NIC");

                    b.Property<DateTime?>("NICExpire")
                        .IsRequired();

                    b.Property<string>("Notes");

                    b.Property<int>("ParameterId");

                    b.Property<int>("Passport");

                    b.Property<DateTime?>("PassportExpire");

                    b.Property<int>("RankCode");

                    b.Property<string>("RankDesc");

                    b.Property<string>("Region");

                    b.Property<DateTime?>("RegistrationDate");

                    b.Property<int>("RelativeGsm1");

                    b.Property<int>("RelativeGsm2");

                    b.Property<int>("ReletiveCode1");

                    b.Property<int>("ReletiveCode2");

                    b.Property<string>("ReletiveName1");

                    b.Property<string>("ReletiveName2");

                    b.Property<string>("ServcieNumber")
                        .IsRequired();

                    b.Property<DateTime?>("Snapshote");

                    b.Property<int?>("UnitId");

                    b.Property<int>("VillageCode");

                    b.Property<string>("VillageDesc");

                    b.Property<int>("WilayaCode");

                    b.Property<string>("WilayaDesc");

                    b.Property<string>("WorkLocation");

                    b.Property<string>("WorkPhone");

                    b.HasKey("PligrimageId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("NIC")
                        .IsUnique();

                    b.HasIndex("ParameterId");

                    b.HasIndex("UnitId");

                    b.ToTable("AlhajjMasters");
                });

            modelBuilder.Entity("Pligrimage.Entities.Buses", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusCapacity");

                    b.Property<string>("BusNo");

                    b.Property<DateTime>("Date");

                    b.Property<int>("FlightId");

                    b.Property<int>("Year");

                    b.HasKey("BusId");

                    b.HasIndex("FlightId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Pligrimage.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlhajYear");

                    b.Property<string>("DescArabic");

                    b.Property<string>("DescEnglish");

                    b.Property<int>("QTY");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Pligrimage.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType");

                    b.Property<string>("DocumnetType");

                    b.Property<string>("FileName");

                    b.Property<string>("Path");

                    b.Property<int>("Year");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Pligrimage.Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArriveDate");

                    b.Property<string>("Direction");

                    b.Property<int>("FlightCapacity");

                    b.Property<DateTime>("FlightDate");

                    b.Property<string>("FlightNo");

                    b.Property<int>("FlightYear");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Pligrimage.Entities.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("DescArabic");

                    b.Property<string>("DescEnglish");

                    b.Property<int>("MaxValue");

                    b.Property<int>("MinValue");

                    b.Property<int>("Value");

                    b.HasKey("ParameterId");

                    b.ToTable("parameters");
                });

            modelBuilder.Entity("Pligrimage.Entities.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlhajYear");

                    b.Property<int>("BusId");

                    b.Property<int>("FlightId");

                    b.Property<int>("PassengerSuppId");

                    b.Property<int>("PligrimageId");

                    b.Property<int>("ResidencesId");

                    b.HasKey("PassengerId");

                    b.HasIndex("BusId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerSuppId");

                    b.HasIndex("PligrimageId")
                        .IsUnique();

                    b.HasIndex("ResidencesId");

                    b.HasIndex("PligrimageId", "AlhajYear")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Pligrimage.Entities.PassengerSupervisors", b =>
                {
                    b.Property<int>("PassengerSuppId");

                    b.Property<int>("Count");

                    b.Property<int>("PligrimageId");

                    b.Property<DateTime>("Year");

                    b.HasKey("PassengerSuppId");

                    b.ToTable("PassengerSupervisors");
                });

            modelBuilder.Entity("Pligrimage.Entities.Residences", b =>
                {
                    b.Property<int>("ResidencesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building");

                    b.Property<int>("Floor");

                    b.Property<int>("Room");

                    b.Property<int>("RoomCapacity");

                    b.Property<DateTime>("Year");

                    b.HasKey("ResidencesId");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("Pligrimage.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlhajYear");

                    b.Property<int>("AllowNumber");

                    b.Property<bool>("ModFlag");

                    b.Property<int>("StandBy");

                    b.Property<int>("UnitCode");

                    b.Property<string>("UnitNameAr");

                    b.Property<string>("UnitNameEn");

                    b.HasKey("UnitId");

                    b.ToTable("units");
                });

            modelBuilder.Entity("Pligrimage.Entities.AlhajjMaster", b =>
                {
                    b.HasOne("Pligrimage.Entities.Category", "Category")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Pligrimage.Entities.Document", "Document")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Parameter", "Parameter")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Unit", "Unit")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Pligrimage.Entities.Buses", b =>
                {
                    b.HasOne("Pligrimage.Entities.Flight", "flight")
                        .WithMany("buses")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.Passenger", b =>
                {
                    b.HasOne("Pligrimage.Entities.Buses", "Buses")
                        .WithMany("Passenger")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Flight", "Flight")
                        .WithMany("Passenger")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.PassengerSupervisors", "PassengerSupervisors")
                        .WithMany("Passenger")
                        .HasForeignKey("PassengerSuppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.AlhajjMaster", "AlhajjMaster")
                        .WithOne("Passenger")
                        .HasForeignKey("Pligrimage.Entities.Passenger", "PligrimageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Residences", "Residences")
                        .WithMany("Passenger")
                        .HasForeignKey("ResidencesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.PassengerSupervisors", b =>
                {
                    b.HasOne("Pligrimage.Entities.AlhajjMaster", "AlhajjMaster")
                        .WithMany("PassengerSupervisors")
                        .HasForeignKey("PassengerSuppId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
