// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pligrimage.Data;

namespace Pligrimage.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191218042359_relativeRelation")]
    partial class relativeRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pligrimage.Entities.AlhajjMaster", b =>
                {
                    b.Property<int>("PligrimageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlhajYear");

                    b.Property<string>("BloodGroup");

                    b.Property<string>("CancelNote");

                    b.Property<int?>("CategoryId");

                    b.Property<int>("ConfirmCode");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<DateTime?>("DateOfEnlistment");

                    b.Property<string>("DoctorNote");

                    b.Property<int?>("DocumentId");

                    b.Property<int>("EmployeeStatus");

                    b.Property<bool>("FitFlag");

                    b.Property<int>("FitResult");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<string>("GSM");

                    b.Property<int>("HrmsUnitCode");

                    b.Property<string>("HrmsUnitDesc");

                    b.Property<string>("NIC")
                        .IsRequired();

                    b.Property<DateTime?>("NICExpire")
                        .IsRequired();

                    b.Property<string>("Notes");

                    b.Property<int>("ParameterId");

                    b.Property<string>("Passport")
                        .IsRequired();

                    b.Property<DateTime?>("PassportExpire");

                    b.Property<string>("PhotoPath");

                    b.Property<int>("RankCode");

                    b.Property<string>("RankDesc");

                    b.Property<string>("Region");

                    b.Property<DateTime?>("RegistrationDate");

                    b.Property<int>("RelativeGsm1");

                    b.Property<int>("RelativeGsm2");

                    b.Property<string>("ReletiveName1");

                    b.Property<string>("ReletiveName2");

                    b.Property<string>("ReletiveRelation1");

                    b.Property<string>("ReletiveRelation2");

                    b.Property<string>("ServcieNumber")
                        .IsRequired();

                    b.Property<DateTime?>("Snapshote");

                    b.Property<int?>("UnitId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("VillageCode");

                    b.Property<string>("VillageDesc");

                    b.Property<int?>("WilayaCode");

                    b.Property<string>("WilayaDesc");

                    b.Property<string>("WorkLocation");

                    b.Property<string>("WorkPhone");

                    b.HasKey("PligrimageId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("NIC")
                        .IsUnique();

                    b.HasIndex("ParameterId");

                    b.HasIndex("UnitId");

                    b.ToTable("AlhajjMasters");
                });

            modelBuilder.Entity("Pligrimage.Entities.Buses", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusCapacity");

                    b.Property<string>("BusNo");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<DateTime>("Date");

                    b.Property<int>("FlightId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("Year");

                    b.HasKey("BusId");

                    b.HasIndex("FlightId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Pligrimage.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlhajYear");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<string>("DescArabic");

                    b.Property<string>("DescEnglish");

                    b.Property<int>("QTY");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Pligrimage.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<string>("DocumnetType");

                    b.Property<string>("FileName");

                    b.Property<string>("Path");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("Year");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Pligrimage.Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArriveDate");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<string>("Direction");

                    b.Property<int>("FlightCapacity");

                    b.Property<DateTime>("FlightDate");

                    b.Property<string>("FlightNo");

                    b.Property<int>("FlightYear");

                    b.Property<int>("ParameterId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("FlightId");

                    b.HasIndex("ParameterId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.AdminLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("AdminLogin");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.ApplicationAuditorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeUser");

                    b.Property<DateTime>("LogDateTime");

                    b.Property<string>("LogRemarks");

                    b.Property<string>("LogType");

                    b.Property<string>("LoggedUserName");

                    b.Property<string>("MachineName");

                    b.Property<string>("OsUser");

                    b.Property<int?>("RoleId");

                    b.Property<int?>("UnitId");

                    b.HasKey("Id");

                    b.ToTable("ApplicationAuditorLogs");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .IsRequired();

                    b.Property<string>("Comment")
                        .IsRequired();

                    b.Property<string>("ControllerName")
                        .IsRequired();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Icone");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("ScreenNameAr")
                        .IsRequired();

                    b.Property<string>("ScreenNameEn")
                        .IsRequired();

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionId")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.RolePermissions", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("PermissionId");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("FullName");

                    b.Property<int?>("HrmsPfNo");

                    b.Property<bool>("IsSysAdmin");

                    b.Property<DateTime?>("LastLoginDate");

                    b.Property<int?>("MainUnitId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Rank");

                    b.Property<int?>("UnitId");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.UserRoles", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.UserService", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ServiceId");

                    b.HasKey("UserId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("UserService");
                });

            modelBuilder.Entity("Pligrimage.Entities.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<string>("DescArabic");

                    b.Property<string>("DescEnglish");

                    b.Property<int>("MaxValue");

                    b.Property<int>("MinValue");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("Value");

                    b.HasKey("ParameterId");

                    b.ToTable("parameters");
                });

            modelBuilder.Entity("Pligrimage.Entities.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlhajYear");

                    b.Property<int>("BusId");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<int>("FlightId");

                    b.Property<int>("PligrimageId");

                    b.Property<int>("ResidencesId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("PassengerId");

                    b.HasIndex("BusId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PligrimageId");

                    b.HasIndex("ResidencesId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Pligrimage.Entities.PassengerSupervisors", b =>
                {
                    b.Property<int>("PassengerSuppId");

                    b.Property<int>("Count");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<int>("PligrimageId");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<DateTime>("Year");

                    b.HasKey("PassengerSuppId");

                    b.ToTable("PassengerSupervisors");
                });

            modelBuilder.Entity("Pligrimage.Entities.Residences", b =>
                {
                    b.Property<int>("ResidencesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<int>("Floor");

                    b.Property<int>("Room");

                    b.Property<int>("RoomCapacity");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<DateTime>("Year");

                    b.HasKey("ResidencesId");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("Pligrimage.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlhajYear");

                    b.Property<int>("AllowNumber");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateOn");

                    b.Property<bool>("ModFlag");

                    b.Property<int>("StandBy");

                    b.Property<int>("UnitCode");

                    b.Property<string>("UnitNameAr");

                    b.Property<string>("UnitNameEn");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("UnitId");

                    b.ToTable("units");
                });

            modelBuilder.Entity("Pligrimage.Entities.AlhajjMaster", b =>
                {
                    b.HasOne("Pligrimage.Entities.Category", "Category")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Pligrimage.Entities.Document", "Document")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("DocumentId");

                    b.HasOne("Pligrimage.Entities.Parameter", "Parameter")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Unit", "Unit")
                        .WithMany("AlhajjMasters")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Pligrimage.Entities.Buses", b =>
                {
                    b.HasOne("Pligrimage.Entities.Flight", "flight")
                        .WithMany("buses")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.Flight", b =>
                {
                    b.HasOne("Pligrimage.Entities.Parameter", "Parameter")
                        .WithMany("Flights")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.RolePermissions", b =>
                {
                    b.HasOne("Pligrimage.Entities.IdentityModels.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.IdentityModels.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.User", b =>
                {
                    b.HasOne("Pligrimage.Entities.Unit", "unit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.UserRoles", b =>
                {
                    b.HasOne("Pligrimage.Entities.IdentityModels.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.IdentityModels.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.IdentityModels.UserService", b =>
                {
                    b.HasOne("Pligrimage.Entities.Unit", "Unit")
                        .WithMany("UserService")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.IdentityModels.User", "User")
                        .WithMany("UserServices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.Passenger", b =>
                {
                    b.HasOne("Pligrimage.Entities.Buses", "Buses")
                        .WithMany("Passenger")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Flight", "Flight")
                        .WithMany("Passenger")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.AlhajjMaster", "AlhajjMaster")
                        .WithMany("Passengers")
                        .HasForeignKey("PligrimageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pligrimage.Entities.Residences", "Residences")
                        .WithMany("Passenger")
                        .HasForeignKey("ResidencesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pligrimage.Entities.PassengerSupervisors", b =>
                {
                    b.HasOne("Pligrimage.Entities.AlhajjMaster", "AlhajjMaster")
                        .WithMany("PassengerSupervisors")
                        .HasForeignKey("PassengerSuppId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
